<#import "parts/common.ftlh" as c>
<#import "/spring.ftl" as spring>
<@c.pageCommon>
<div class="container" align="center">
    <h1 id="welcome_text" class="my-3"><@spring.message "label.welcome"/></h1>
    <div id="welcome_text"><h3><@spring.message "label.myproject"/></h3></div>
</div>

<div class="container my-3">

    <#--<div class="row">-->
        <#--<div class="col-sm">-->
            <#--1-->
        <#--</div>-->
    <#--</div>-->

</div>
</@c.pageCommon>